/* Vesta Language Institute — language switcher (Persian / English)
   Persian text lives in the HTML (default). English strings are stored below
   and swapped in by key (data-i18n / data-i18n-attr). */
(function () {
  'use strict';
  var EN = {
"k1": "Vesta Language Institute — English courses, in-person and online classes, and free learning tools",
"k2": "Vesta Language Institute logo",
"k3": "Open menu",
"k4": "Vesta",
"k5": "Vesta | Language Institute",
"k6": "📞 0919-3191750",
"k7": "Instagram",
"k8": "Telegram",
"k9": "Home",
"k10": "About us",
"k11": "Courses",
"k12": "Learning tools",
"k13": "Contact",
"k14": "Student login",
"k15": "Vesta Language Institute",
"k16": "Learn English the <em>right</em> way, for real-life use",
"k17": "Small-group English classes with a special focus on children and teenagers, directed by Dr. Behnaz Pahlavani\n          and taught by teachers with university degrees and professional teaching certifications, plus free learning tools for practice at home.",
"k18": "View courses",
"k19": "Free registration advice",
"k20": "20+",
"k21": "Director's years of teaching",
"k22": "5",
"k23": "Specialist teachers",
"k24": "Online and in person",
"k25": "Class formats",
"k26": "Vesta Language Institute",
"k27": "Course registration, class news, and online learning resources",
"k28": "01",
"k29": "Courses",
"k30": "Browse syllabi and class schedules",
"k31": "View →",
"k32": "02",
"k33": "Offline practice files with audio playback",
"k34": "03",
"k35": "Course registration",
"k36": "Request registration and class advice",
"k37": "04",
"k38": "Student portal",
"k39": "Sign in and follow your course",
"k40": "Our team",
"k41": "Meet Vesta's director and teachers",
"k42": "Teachers who specialize in children, young learners, and teenagers, led by a director with more than 20 years of experience in English language education.",
"k43": "BP",
"k44": "Dr. Behnaz Pahlavani",
"k45": "Founder and Director, Vesta Language Institute",
"k46": "Holds a Ph.D. in English Language Teaching; author and researcher in language education and a recognized Outstanding Provincial English Language Teacher, with teaching experience at universities, high schools, and language institutes.",
"k47": "View full profile",
"k48": "SJ",
"k49": "Samaneh Jooj",
"k50": "Young Learners and Teens English Teacher",
"k51": "RN",
"k52": "Reyhaneh Nikmanesh",
"k53": "MZ",
"k54": "Mehrsa Zeinali",
"k55": "Teen English Teacher",
"k56": "ZJ",
"k57": "Zahra Jabari",
"k58": "Children’s English Teacher",
"k59": "Popular courses",
"k60": "A course that fits your goal",
"k61": "A sample of current courses — full syllabi are on the Courses page.",
"k62": "Beginner",
"k63": "Start from the basics: speaking skills and everyday vocabulary for new learners.",
"k64": "Duration: <strong>10 weeks</strong>",
"k65": "Capacity: <strong>8 students</strong>",
"k66": "Course details",
"k67": "Intermediate",
"k68": "Build fluent conversation, practical grammar, and readiness for international exams.",
"k69": "Duration: <strong>12 weeks</strong>",
"k70": "Capacity: <strong>10 students</strong>",
"k71": "Exam preparation",
"k72": "IELTS strategies, practice in all four skills, and simulated test sessions.",
"k73": "Duration: <strong>8 weeks</strong>",
"k74": "Capacity: <strong>6 students</strong>",
"k75": "Learn anytime",
"k76": "Offline learning tools",
"k77": "Downloadable practice files that open in your browser without internet and with audio playback.",
"k78": "Practice anywhere, no internet needed",
"k79": "Each file includes text, exercises, and an audio player (TTS). Just download it and open it in your phone or computer browser.",
"k80": "See all tools",
"k81": "Everyday conversations — beginner",
"k82": "24 common phrases with pronunciation",
"k83": "With audio",
"k84": "Travel and airport vocabulary",
"k85": "40 useful words and expressions",
"k86": "Grammar: verb tenses",
"k87": "Summary and interactive practice",
"k88": "Registration",
"k89": "Register for a course",
"k90": "Fill in the form and a Vesta registration advisor will contact you.",
"k91": "We reply within 24 working hours",
"k92": "Free advice to determine your level",
"k93": "You are notified of the class start date once enrollment is complete",
"k94": "Full name",
"k95": "Phone number",
"k96": "Email",
"k97": "Course of interest",
"k98": "Foundation A1 — Beginner",
"k99": "Intermediate B1-B2 — Intermediate",
"k100": "IELTS Preparation — Exam preparation",
"k101": "Not sure yet — I need advice",
"k102": "Send registration request",
"k103": "Your details are used only so our registration advisor can contact you.",
"k104": "Vesta student portal",
"k105": "View your course status, weekly exercises, and class audio files in the student portal — launching soon.",
"k106": "View portal",
"k107": "Vesta Language Institute: quality teaching, experienced teachers, and up-to-date learning resources.",
"k108": "Quick links",
"k109": "Account",
"k110": "Contact us",
"k111": "0919-3191750",
"k112": "Address and map",
"k113": "© Vesta Language Institute. All rights reserved.",
"k114": "About Vesta Language Institute: its director, teachers, and story",
"k115": "About us | Vesta",
"k116": "About Vesta Language Institute",
"k117": "An institute focused on practical English teaching, with small classes, teachers who specialize in each age group, and individual follow-up for every learner, directed by Dr. Behnaz Pahlavani.",
"k118": "Our mission",
"k119": "We make language learning simple and practical",
"k120": "Vesta was founded on the belief that language teaching should be results-driven, personalized, and measurable — not just memorizing grammar rules. Our teaching approach is built on the psychology of learning, motivation, and effective classroom management.",
"k121": "Goal-driven teaching",
"k122": "Every learner takes a placement test before starting, so the learning path fits their goal (conversation, exams, or work).",
"k123": "Small classes",
"k124": "Class sizes are kept limited so every learner gets enough practice and feedback.",
"k125": "Continuous progress tracking",
"k126": "Regular assessment and progress reports help each learner see their learning path clearly.",
"k127": "Vesta's teachers",
"k128": "A director and teachers with university degrees, professional teaching certification, and years of experience teaching children, young learners, and teenagers.",
"k129": "Professional profile",
"k130": "Dr. Behnaz Pahlavani holds a Ph.D. in English Language Teaching and has more than 20 years of professional experience in English language education, with teaching experience across universities, high schools, and language institutes.",
"k131": "Her professional expertise encompasses English language teaching, language education research, teacher education, educational program development, and academic management.",
"k132": "Academic and professional qualifications",
"k133": "Ph.D. in English Language Teaching",
"k134": "More than 20 years of professional experience in English language education",
"k135": "Teaching experience at universities, high schools, and language institutes",
"k136": "Author and researcher in the field of English language education",
"k137": "Recognized as an Outstanding Provincial English Language Teacher",
"k138": "Founder and Director of Vesta Language Institute",
"k139": "Specialized training and areas of expertise",
"k140": "Educational Psychology",
"k141": "Psychology of Learning",
"k142": "Child and Adolescent Psychology",
"k143": "Psychology of Teaching",
"k144": "Motivation and Language Learning",
"k145": "Classroom Management",
"k146": "Creative Teaching",
"k147": "Teaching Methodology and Instructional Techniques",
"k148": "Professional areas",
"k149": "English Language Teaching (ELT)",
"k150": "Teacher Education and Professional Development",
"k151": "Language Education Research",
"k152": "Educational Program Design and Development",
"k153": "Young Learner and Adolescent Education",
"k154": "Academic and Educational Management",
"k155": "Samaneh Jooj holds a B.A. in English Language Teaching and English Translation and has more than 10 years of professional experience in English language education, with a particular focus on young learners and teenagers.",
"k156": "Qualifications",
"k157": "B.A. in English Language Teaching and English Translation",
"k158": "TTC certified",
"k159": "More than 10 years of teaching experience",
"k160": "Professional areas",
"k161": "Young Learner Education",
"k162": "Teen English Education",
"k163": "Teaching Methodology",
"k164": "Child-Centered Language Teaching",
"k165": "Reyhaneh Nikmanesh holds a B.A. in English Language Teaching and has more than 6 years of professional experience in English language education, with a particular focus on young learners and teenagers.",
"k166": "B.A. in English Language Teaching",
"k167": "More than 6 years of teaching experience",
"k168": "Motivation in Language Learning",
"k169": "Mehrsa Zeinali is an experienced English language teacher with 5 years of professional teaching experience, specializing in English language education for teenagers.",
"k170": "5 years of teaching experience",
"k171": "Zahra Jabari is an experienced English language teacher with 5 years of professional teaching experience, specializing in English language education for children.",
"k172": "Children’s English Education",
"k173": "Our journey",
"k174": "Vesta at a glance",
"k175": "Foundation",
"k176": "Vesta was founded by Dr. Behnaz Pahlavani, drawing on more than 20 years of experience in English language education, with the aim of offering practical, high-quality teaching.",
"k177": "Growing our courses",
"k178": "Specialized exam-preparation courses and online classes were added to our programs.",
"k179": "Today",
"k180": "Vesta's team of five experienced teachers — from the director to our children's and teen specialists — supports learners on their English language journey.",
"k181": "Vesta English courses from beginner level to international exam preparation",
"k182": "Courses | Vesta",
"k183": "Vesta courses",
"k184": "From the basics to international exam preparation — every course starts with a free placement test.",
"k185": "All courses",
"k186": "Advanced",
"k187": "Online",
"k188": "Foundation A1",
"k189": "No prerequisites. Focus on listening, speaking, and common everyday vocabulary.",
"k190": "Conversation basics and simple sentence building",
"k191": "300 practical everyday words",
"k192": "Listening practice with a weekly audio file",
"k193": "6 of 8 seats filled",
"k194": "Duration: <strong>10 weeks</strong>",
"k195": "Starts: <strong>5 Mehr</strong>",
"k196": "Register for this course",
"k197": "Foundation A2",
"k198": "Consolidate basic grammar and grow your vocabulary for simple everyday conversations.",
"k199": "Simple present and past tenses",
"k200": "Conversation in common situations (shopping, restaurants, travel)",
"k201": "Pronunciation practice with the audio player",
"k202": "3 of 8 seats filled",
"k203": "Starts: <strong>12 Mehr</strong>",
"k204": "Intermediate B1",
"k205": "More fluent conversation, practical grammar, and the start of simple writing practice.",
"k206": "Perfect tenses and conditionals",
"k207": "Free conversation on current topics",
"k208": "Weekly writing practice with teacher feedback",
"k209": "8 of 10 seats filled",
"k210": "Duration: <strong>12 weeks</strong>",
"k211": "Starts: <strong>8 Mehr</strong>",
"k212": "Intermediate B2",
"k213": "Mastery of everyday and work conversation, and readiness to move on to the advanced level.",
"k214": "Conversation in work and formal settings",
"k215": "More advanced grammar and correction of common mistakes",
"k216": "Listening practice with authentic English audio",
"k217": "4 of 10 seats filled",
"k218": "Starts: <strong>15 Mehr</strong>",
"k219": "IELTS Preparation",
"k220": "IELTS strategies and practice in all four skills with simulated test sessions.",
"k221": "Reading and Listening techniques",
"k222": "Writing Task 1 and 2 practice with feedback",
"k223": "Simulated Speaking session",
"k224": "5 of 6 seats filled",
"k225": "Duration: <strong>8 weeks</strong>",
"k226": "Starts: <strong>10 Mehr</strong>",
"k227": "Free online conversation",
"k228": "A small online class for conversation practice on current topics, with no need to attend in person.",
"k229": "Groups of up to 5 students",
"k230": "One 60-minute session per week",
"k231": "Suitable for B1 level and above",
"k232": "2 of 5 seats filled",
"k233": "Duration: <strong>Ongoing</strong>",
"k234": "Starts: <strong>Every week</strong>",
"k235": "There are no courses in this category right now. Contact us to hear about upcoming courses.",
"k236": "By age group",
"k237": "Teachers who specialize in each age group",
"k238": "Our programs run under the direction of Dr. Behnaz Pahlavani, who holds a Ph.D. in English Language Teaching and specializes in educational program design.",
"k239": "Children",
"k240": "English education for children, taught by a teacher who specializes in this age group and in classroom management.",
"k241": "Young learners",
"k242": "Child-centered, motivating instruction for young learners, built on modern teaching methods and classroom management.",
"k243": "Teenagers",
"k244": "English classes for teenagers with teachers experienced in teaching and motivating this age group.",
"k245": "Not sure of your level?",
"k246": "Take a short, free placement test and we will recommend the most suitable course for you.",
"k247": "Request a free placement test",
"k248": "Contact Vesta Language Institute and register for courses",
"k249": "Map of Vesta Language Institute",
"k250": "Briefly describe your request",
"k251": "Contact | Vesta",
"k252": "Contact Vesta",
"k253": "Have a question about our courses or want to register? Reach us in any of the ways below.",
"k254": "Institute address",
"k255": "Motahari Blvd., Darab, Fars, Iran",
"k256": "Institute management",
"k257": "Dr. Behnaz Pahlavani, Founder and Director",
"k258": "Phone",
"k259": "Response hours",
"k260": "Saturday to Thursday, 9:00 to 19:00",
"k261": "Getting here",
"k262": "Motahari Blvd., Darab",
"k263": "Message subject",
"k264": "Question about courses",
"k265": "Registration and placement test",
"k266": "Working with Vesta",
"k267": "Other",
"k268": "Your message",
"k269": "Send message",
"k270": "We reply to your message within 24 working hours.",
"k271": "Foundation A2 — Beginner",
"k272": "Intermediate B1 — Intermediate",
"k273": "Intermediate B2 — Intermediate",
"k274": "Student sign-in to the Vesta portal",
"k275": "Student login | Vesta",
"k276": "Sign in to see your course status and learning files",
"k277": "Mobile number",
"k278": "Password",
"k279": "Sign in to portal",
"k280": "or",
"k281": "I haven't registered yet",
"k282": "Forgot your password?",
"k283": "Contact support",
"k284": "Offline English learning files with audio — Vesta Language Institute",
"k285": "Learning tools | Vesta",
"k286": "Standalone HTML files that open without internet and include an audio player (TTS) for pronunciation practice.",
"k287": "How to use",
"k288": "Get ready to practice in three steps",
"k289": "1",
"k290": "Save the file you want with the Download button.",
"k291": "2",
"k292": "Open the file in your phone or computer browser — no internet needed.",
"k293": "3",
"k294": "Use the play button to practice the correct pronunciation of each phrase.",
"k295": "Beginner-level files",
"k296": "Everyday conversations",
"k297": "24 common phrases for introducing yourself, greetings, and simple shopping.",
"k298": "Size: 0.1 MB",
"k299": "Download file",
"k300": "Numbers and time",
"k301": "Learn counting, telling time, and dates in English with listening practice.",
"k302": "At the restaurant",
"k303": "Useful expressions and dialogues for ordering food and booking a table.",
"k304": "Coming soon",
"k305": "Intermediate and exam preparation",
"k306": "Higher-level files",
"k307": "40 useful words and expressions for travel and getting through the airport.",
"k308": "A practical summary of present, past, and future tenses with interactive practice.",
"k309": "IELTS vocabulary — part 1",
"k310": "High-frequency IELTS vocabulary with examples and correct pronunciation.",
"k311": "Part of the Vesta family?",
"k312": "Active learners get the full set of learning files and exclusive weekly exercises in their portal.",
"k313": "Sign in to the student portal"
};
  var KEY = 'vesta-lang';

  function readLang() {
    try {
      var q = new URLSearchParams(location.search).get('lang');
      if (q === 'en' || q === 'fa') return q;
    } catch (e) {}
    try { return localStorage.getItem(KEY) === 'en' ? 'en' : 'fa'; } catch (e) { return 'fa'; }
  }

  function apply(lang) {
    var root = document.documentElement;
    root.lang = lang;
    root.dir = lang === 'en' ? 'ltr' : 'rtl';

    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      if (el.getAttribute('data-fa') === null) el.setAttribute('data-fa', el.innerHTML);
      el.innerHTML = lang === 'en' ? EN[el.getAttribute('data-i18n')] : el.getAttribute('data-fa');
    });

    document.querySelectorAll('[data-i18n-attr]').forEach(function (el) {
      el.getAttribute('data-i18n-attr').split(';').forEach(function (pair) {
        var p = pair.split(':'), name = p[0], key = p[1], store = 'data-fa-' + name;
        if (el.getAttribute(store) === null) el.setAttribute(store, el.getAttribute(name) || '');
        el.setAttribute(name, lang === 'en' ? EN[key] : el.getAttribute(store));
      });
    });

    document.querySelectorAll('.lang-switch button').forEach(function (b) {
      b.setAttribute('aria-pressed', String(b.getAttribute('data-lang') === lang));
    });
  }

  /* helper for scripted messages: L('فارسی', 'English') */
  window.L = function (fa, en) { return document.documentElement.lang === 'en' ? en : fa; };

  document.querySelectorAll('.lang-switch button').forEach(function (b) {
    b.addEventListener('click', function () {
      var lang = b.getAttribute('data-lang');
      try { localStorage.setItem(KEY, lang); } catch (e) {}
      apply(lang);
    });
  });

  apply(readLang());
})();
