/* Vesta Language Institute — language switcher (Persian / English)
   Persian text lives in the HTML (default). English strings are stored below
   and swapped in by key (data-i18n / data-i18n-attr). */
(function () {
  'use strict';
  var EN = {
"k1": "Vesta Language Institute — English learning pathways from age 4 to adults, exam preparation, teacher training, and free learning tools",
"k2": "Vesta Language Institute logo",
"k3": "Open menu",
"k4": "Vesta",
"k5": "Vesta | Language Institute",
"k6": "📞 0919-3191750",
"k7": "Instagram",
"k8": "Telegram",
"k9": "Home",
"k10": "About us",
"k11": "Courses",
"k12": "Learning tools",
"k13": "Contact",
"k14": "Student login",
"k15": "Vesta Language Institute",
"k16": "Learn English the <em>right</em> way, for real-life use",
"k17": "From the first language-learning experiences at age 4 to advanced adult courses and teacher training: a purposeful, step-by-step path,\n          directed by Dr. Behnaz Pahlavani and taught by teachers with university degrees and professional teaching certifications.",
"k18": "View courses",
"k19": "Free registration advice",
"k20": "20+",
"k21": "Director's years of teaching",
"k22": "5",
"k23": "Specialist teachers",
"k24": "7",
"k25": "Learning pathways, from age 4 to teacher training",
"k26": "Vesta Language Institute",
"k27": "Learning pathways, course registration, and free learning resources",
"k28": "01",
"k29": "Courses",
"k30": "Browse learning pathways and syllabi",
"k31": "View →",
"k32": "02",
"k33": "Offline practice files with audio playback",
"k34": "03",
"k35": "Course registration",
"k36": "Request registration and class advice",
"k37": "04",
"k38": "Student portal",
"k39": "Sign in and follow your course",
"k40": "Our team",
"k41": "Meet Vesta's director and teachers",
"k42": "Teachers who specialize in children, young learners, and teenagers, led by a director with more than 20 years of experience in English language education.",
"k43": "BP",
"k44": "Dr. Behnaz Pahlavani",
"k45": "Founder and Director, Vesta Language Institute",
"k46": "Holds a Ph.D. in English Language Teaching; author and researcher in language education and a recognized Outstanding Provincial English Language Teacher, with teaching experience at universities, high schools, and language institutes.",
"k47": "View full profile",
"k48": "SJ",
"k49": "Samaneh Jooj",
"k50": "Young Learners and Teens English Teacher",
"k51": "RN",
"k52": "Reyhaneh Nikmanesh",
"k53": "MZ",
"k54": "Mehrsa Zeinali",
"k55": "Teen English Teacher",
"k56": "ZJ",
"k57": "Zahra Jabari",
"k58": "Children’s English Teacher",
"k59": "Learning pathways",
"k60": "A path matched to your age, level, and goal",
"k61": "From children’s classes to advanced courses, exam preparation, and teacher training — every stage uses reputable resources and a skills-based approach.",
"k62": "English for children",
"k63": "Specialist English teaching for teenagers",
"k64": "General courses for young adults and adults",
"k65": "Developing advanced language skills",
"k66": "Specialist courses in Speaking, Listening, Reading, Writing, Grammar, and Vocabulary",
"k67": "IELTS, EPT, MSRT, and the university entrance exam (Konkur)",
"k68": "Teacher training and professional development",
"k69": "See all pathways and syllabi",
"k70": "Learn anytime",
"k71": "Offline learning tools",
"k72": "Downloadable practice files that open in your browser without internet and with audio playback.",
"k73": "Practice anywhere, no internet needed",
"k74": "Each file includes text, exercises, and an audio player (TTS). Just download it and open it in your phone or computer browser.",
"k75": "See all tools",
"k76": "Everyday conversations — beginner",
"k77": "24 common phrases with pronunciation",
"k78": "With audio",
"k79": "Travel and airport vocabulary",
"k80": "40 useful words and expressions",
"k81": "Grammar: verb tenses",
"k82": "Summary and interactive practice",
"k83": "Registration",
"k84": "Register for a course",
"k85": "Fill in the form and a Vesta registration advisor will contact you.",
"k86": "We reply within 24 working hours",
"k87": "Free advice to determine your level",
"k88": "You are notified of the class start date once enrollment is complete",
"k89": "Full name",
"k90": "Phone number",
"k91": "Email",
"k92": "Course of interest",
"k93": "Early Years (ages 4 to 6)",
"k94": "Primary English — Family and Friends",
"k95": "Teens — Connect",
"k96": "General English — Four Corners",
"k97": "Advanced English — Passages",
"k98": "Skill-Based Courses",
"k99": "IELTS Preparation",
"k100": "EPT and MSRT Preparation",
"k101": "English for Entrance Exams (Konkur)",
"k102": "TTC — Teacher Training",
"k103": "TKT Preparation",
"k104": "Not sure yet — I need advice",
"k105": "Send registration request",
"k106": "Your details are used only so our registration advisor can contact you.",
"k107": "Vesta student portal",
"k108": "View your course status, weekly exercises, and class audio files in the student portal — launching soon.",
"k109": "View portal",
"k110": "Vesta Language Institute: quality teaching, experienced teachers, and up-to-date learning resources.",
"k111": "Quick links",
"k112": "Account",
"k113": "Contact us",
"k114": "0919-3191750",
"k115": "Address and map",
"k116": "© Vesta Language Institute. All rights reserved.",
"k117": "About Vesta Language Institute: its director, teachers, and story",
"k118": "About us | Vesta",
"k119": "About Vesta Language Institute",
"k120": "An institute focused on purposeful, step-by-step English teaching, from age 4 to adults and teacher training, with teachers who specialize in each age group, directed by Dr. Behnaz Pahlavani.",
"k121": "Our mission",
"k122": "We make language learning simple and practical",
"k123": "Vesta was founded on the belief that language teaching should be results-driven, personalized, and measurable — not just memorizing grammar rules. Our teaching approach is built on the psychology of learning, motivation, and effective classroom management.",
"k124": "Why Vesta?",
"k125": "A structured curriculum based on reputable resources",
"k126": "Teaching methods matched to the learner’s age, needs, and developmental stage",
"k127": "Genuine attention to Listening, Speaking, Reading, and Writing skills",
"k128": "A path designed around the learner’s real goal",
"k129": "Ongoing assessment and monitoring of progress",
"k130": "Attention to the professional growth of learners and teachers",
"k131": "Vesta's teachers",
"k132": "A director and teachers with university degrees, professional teaching certification, and years of experience teaching children, young learners, and teenagers.",
"k133": "Professional profile",
"k134": "Dr. Behnaz Pahlavani holds a Ph.D. in English Language Teaching and has more than 20 years of professional experience in English language education, with teaching experience across universities, high schools, and language institutes.",
"k135": "Her professional expertise encompasses English language teaching, language education research, teacher education, educational program development, and academic management.",
"k136": "Academic and professional qualifications",
"k137": "Ph.D. in English Language Teaching",
"k138": "More than 20 years of professional experience in English language education",
"k139": "Teaching experience at universities, high schools, and language institutes",
"k140": "Author and researcher in the field of English language education",
"k141": "Recognized as an Outstanding Provincial English Language Teacher",
"k142": "Founder and Director of Vesta Language Institute",
"k143": "Specialized training and areas of expertise",
"k144": "Educational Psychology",
"k145": "Psychology of Learning",
"k146": "Child and Adolescent Psychology",
"k147": "Psychology of Teaching",
"k148": "Motivation and Language Learning",
"k149": "Classroom Management",
"k150": "Creative Teaching",
"k151": "Teaching Methodology and Instructional Techniques",
"k152": "Professional areas",
"k153": "English Language Teaching (ELT)",
"k154": "Teacher Education and Professional Development",
"k155": "Language Education Research",
"k156": "Educational Program Design and Development",
"k157": "Young Learner and Adolescent Education",
"k158": "Academic and Educational Management",
"k159": "Samaneh Jooj holds a B.A. in English Language Teaching and English Translation and has more than 10 years of professional experience in English language education, with a particular focus on young learners and teenagers.",
"k160": "Qualifications",
"k161": "B.A. in English Language Teaching and English Translation",
"k162": "TTC certified",
"k163": "More than 10 years of teaching experience",
"k164": "Professional areas",
"k165": "Young Learner Education",
"k166": "Teen English Education",
"k167": "Teaching Methodology",
"k168": "Child-Centered Language Teaching",
"k169": "Reyhaneh Nikmanesh holds a B.A. in English Language Teaching and has more than 6 years of professional experience in English language education, with a particular focus on young learners and teenagers.",
"k170": "B.A. in English Language Teaching",
"k171": "More than 6 years of teaching experience",
"k172": "Motivation in Language Learning",
"k173": "Mehrsa Zeinali is an experienced English language teacher with 5 years of professional teaching experience, specializing in English language education for teenagers.",
"k174": "5 years of teaching experience",
"k175": "Zahra Jabari is an experienced English language teacher with 5 years of professional teaching experience, specializing in English language education for children.",
"k176": "Children’s English Education",
"k177": "Our journey",
"k178": "Vesta at a glance",
"k179": "Foundation",
"k180": "Vesta was founded by Dr. Behnaz Pahlavani, drawing on more than 20 years of experience in English language education, with the aim of offering practical, high-quality teaching.",
"k181": "Our pathways",
"k182": "Learning at Vesta starts at age 4 and continues through general and advanced courses, exam preparation, and teacher training.",
"k183": "Today",
"k184": "Vesta's team of five experienced teachers — from the director to our children's and teen specialists — supports learners on their English language journey.",
"k185": "Vesta English learning pathways: children, teens, general, advanced, exam preparation, and teacher training",
"k186": "Learning pathways | Vesta",
"k187": "The English learning path at Vesta",
"k188": "From the first language-learning experiences at age 4 to advanced adult courses and teacher training.",
"k189": "Vesta’s learning pathways",
"k190": "At Vesta Language Institute, learning English is a purposeful, step-by-step path, tailored to each learner’s age, level, needs, and goals.",
"k191": "From the first language-learning experiences at age 4 to advanced adult courses and teacher training, every stage is built on reputable teaching resources and a skills-based approach.",
"k192": "At Vesta, we find the right path for every learner.",
"k193": "Placement test",
"k194": "Educational consultation",
"k195": "Starting English at age 4",
"k196": "In the early years, our goal is to build a positive, natural, and enjoyable experience of English.",
"k197": "Through games, stories, songs, pictures, movement, and interactive activities, children become familiar with the language and gradually develop their first skills.",
"k198": "Why this course?",
"k199": "Suited to the child’s age and cognitive ability",
"k200": "Learning through play and activities",
"k201": "Building confidence in using the language",
"k202": "Creating a solid base for the next stages",
"k203": "Vesta’s message to parents",
"k204": "At this age, becoming interested in English matters more than memorizing English. We help children begin the language with enjoyment, confidence, and a positive experience.",
"k205": "Age",
"k206": "4 to 6 years",
"k207": "Level",
"k208": "Resources",
"k209": "Focus",
"k210": "Register or ask for advice",
"k211": "Structured English learning for primary-school children",
"k212": "At this stage, the child moves from early introductions into a more structured, skills-based path.",
"k213": "The Family and Friends series, with its focus on language, phonics, and communication skills, creates a solid base for the rest of the learning journey.",
"k214": "Course features",
"k215": "Age-appropriate teaching",
"k216": "Strengthening the four main skills",
"k217": "Developing vocabulary and language structures",
"k218": "Communicative and interactive activities",
"k219": "Preparation for higher levels",
"k220": "Vesta’s goal",
"k221": "The learner should not just finish the book, but be able to use what they have learned in real communication.",
"k222": "Age group",
"k223": "Primary-school children",
"k224": "Main resource",
"k225": "Core skills",
"k226": "Along with",
"k227": "English in the world of teenagers",
"k228": "The Connect course is designed for teenagers to learn English through age-appropriate topics, in a practical, communicative way.",
"k229": "At this stage, learners move from learning basic structures toward more real-world use of the language.",
"k230": "Course features",
"k231": "Topics that fit teenagers’ world",
"k232": "Communicative activities",
"k233": "Building confidence in Speaking",
"k234": "Vocabulary development",
"k235": "Developing all four skills together",
"k236": "Teenagers, about 11 to 15 years",
"k237": "Resource",
"k238": "Overall level",
"k239": "Focus",
"k240": "Skills",
"k241": "English for real life",
"k242": "Four Corners teaches English in real, practical situations and prepares learners to communicate effectively in daily life.",
"k243": "Suitable for people who want to:",
"k244": "Strengthen their conversation",
"k245": "Gain more confidence in speaking",
"k246": "Learn English systematically",
"k247": "Develop the four main skills together",
"k248": "Get ready for higher levels",
"k249": "Young adults and adults",
"k250": "Course focus",
"k251": "Passages is the more advanced stage of Vesta’s General English path, for learners who want to use English more fluently, accurately, and professionally.",
"k252": "At this stage, the learner:",
"k253": "Talks about more complex topics",
"k254": "Expands their vocabulary",
"k255": "Analyzes more advanced texts",
"k256": "Strengthens the ability to express and defend their views",
"k257": "Becomes better prepared for academic and professional settings",
"k258": "The learning path within the CEFR framework",
"k259": "One path, step by step",
"k260": "At Vesta, each learner enters the most suitable stage based on their real level, age, and learning goal.",
"k261": "“A learner’s final level is not decided by the name of a book alone; it is determined by assessing their real ability in the language skills.”",
"k262": "Single-skill courses",
"k263": "Not every learner needs the same path. At Vesta, specialist single-skill courses are offered for people who want to focus on one specific skill.",
"k264": "To strengthen conversation, speaking fluency, pronunciation, and confidence in Speaking.",
"k265": "To strengthen understanding of natural speech and improve listening processing.",
"k266": "To increase reading speed and comprehension and prepare for academic and exam texts.",
"k267": "To strengthen structure, coherence, accuracy, and writing skill.",
"k268": "For learners who want to learn grammar in a deep, systematic, practical way.",
"k269": "To expand vocabulary and turn passive words into words learners can actually use.",
"k270": "Suitable for",
"k271": "Learners who need to strengthen one specific skill, are preparing for an exam, or want to develop a particular skill intensively alongside a general course.",
"k272": "Purposeful IELTS preparation",
"k273": "Vesta’s IELTS preparation course is designed for learners with a clear goal of taking the international IELTS exam.",
"k274": "Alongside skills training, learners become familiar with:",
"k275": "Learning path",
"k276": "Before the course begins, the learner’s level and target Band Score are assessed so the learning path can be designed around their needs.",
"k277": "Suitable for:",
"k278": "Immigration",
"k279": "Study",
"k280": "Career goals",
"k281": "Continuing studies at international universities",
"k282": "People who need a specific IELTS score",
"k283": "Our goal",
"k284": "It is not only about learning exam techniques, but about building the language skills needed to perform well in the exam.",
"k285": "Four core skills",
"k286": "Register or ask about IELTS",
"k287": "Targeted preparation for university exams",
"k288": "Vesta’s EPT and MSRT preparation courses are designed for candidates looking for an organized, focused path to exam readiness.",
"k289": "In these courses:",
"k290": "The exam structure is reviewed",
"k291": "Answering tips and techniques are taught",
"k292": "The required vocabulary and grammar are strengthened",
"k293": "Reading skills are developed",
"k294": "Time management and exam strategy are practiced",
"k295": "Core areas",
"k296": "Graduate students and candidates for the EPT and MSRT exams",
"k297": "Entrance-exam English: focused and exam-oriented",
"k298": "Vesta’s entrance-exam English classes are designed for students who want to approach the English section with an organized, focused plan.",
"k299": "Course goals",
"k300": "Mastery of high-frequency vocabulary",
"k301": "Stronger grammar",
"k302": "Better reading comprehension",
"k303": "Familiarity with question patterns",
"k304": "Greater speed and accuracy in answering",
"k305": "Vesta’s advice",
"k306": "Success in an exam depends not only on knowing the material; study method, time management, and understanding question structure matter too.",
"k307": "Teacher Training Course (TTC)",
"k308": "Vesta’s TTC (Teacher Training Course) is designed for people who want to turn their knowledge of English into professional teaching skills.",
"k309": "The course combines theory, teaching methods, lesson design, and practical classroom experience.",
"k310": "TTC core components",
"k311": "What makes Vesta’s TTC different",
"k312": "In the TTC, the aim is not only to learn “teaching methods”; participants get the chance to design, teach, receive feedback, and improve their performance.",
"k313": "People interested in teaching English",
"k314": "New teachers",
"k315": "Graduates of related fields",
"k316": "Experienced teachers seeking professional development",
"k317": "People planning to enter language teaching professionally",
"k318": "Course outcome",
"k319": "By the end of the course, participants will be familiar with the key principles of:",
"k320": "Register or ask about the TTC",
"k321": "A teacher’s professional growth never stops",
"k322": "In addition to training new teachers, Vesta offers paths for developing the knowledge and professional skills of English teachers.",
"k323": "The TKT preparation course suits teachers who want to deepen their specialist knowledge of English language teaching and prepare for the TKT exam.",
"k324": "Main areas",
"k325": "Register or ask about the TKT",
"k326": "We believe language teaching is effective when it is purposeful, matched to the learner, and measurable.",
"k327": "Vesta: a place to learn the language, grow your skills, and build a more professional future.",
"k328": "By age group",
"k329": "Teachers who specialize in each age group",
"k330": "Our programs run under the direction of Dr. Behnaz Pahlavani, who holds a Ph.D. in English Language Teaching and specializes in educational program design.",
"k331": "Children",
"k332": "English education for children, taught by a teacher who specializes in this age group and in classroom management.",
"k333": "Young learners",
"k334": "Child-centered, motivating instruction for young learners, built on modern teaching methods and classroom management.",
"k335": "Teenagers",
"k336": "English classes for teenagers with teachers experienced in teaching and motivating this age group.",
"k337": "Contact Vesta Language Institute and register for courses",
"k338": "Map of Vesta Language Institute",
"k339": "Briefly describe your request",
"k340": "Contact | Vesta",
"k341": "Contact Vesta",
"k342": "Have a question about our courses or want to register? Reach us in any of the ways below.",
"k343": "Institute address",
"k344": "Motahari Blvd., Darab, Fars, Iran",
"k345": "Institute management",
"k346": "Dr. Behnaz Pahlavani, Founder and Director",
"k347": "Phone",
"k348": "Response hours",
"k349": "Saturday to Thursday, 9:00 to 19:00",
"k350": "Getting here",
"k351": "Motahari Blvd., Darab",
"k352": "Message subject",
"k353": "Question about courses",
"k354": "Registration and placement test",
"k355": "Working with Vesta",
"k356": "Teacher training (TTC and TKT)",
"k357": "Other",
"k358": "Your message",
"k359": "Send message",
"k360": "We reply to your message within 24 working hours.",
"k361": "Student sign-in to the Vesta portal",
"k362": "Student login | Vesta",
"k363": "Sign in to see your course status and learning files",
"k364": "Mobile number",
"k365": "Password",
"k366": "Sign in to portal",
"k367": "or",
"k368": "I haven't registered yet",
"k369": "Forgot your password?",
"k370": "Contact support",
"k371": "Offline English learning files with audio — Vesta Language Institute",
"k372": "Learning tools | Vesta",
"k373": "Standalone HTML files that open without internet and include an audio player (TTS) for pronunciation practice.",
"k374": "How to use",
"k375": "Get ready to practice in three steps",
"k376": "1",
"k377": "Save the file you want with the Download button.",
"k378": "2",
"k379": "Open the file in your phone or computer browser — no internet needed.",
"k380": "3",
"k381": "Use the play button to practice the correct pronunciation of each phrase.",
"k382": "Beginner",
"k383": "Beginner-level files",
"k384": "Everyday conversations",
"k385": "24 common phrases for introducing yourself, greetings, and simple shopping.",
"k386": "Size: 0.1 MB",
"k387": "Download file",
"k388": "Numbers and time",
"k389": "Learn counting, telling time, and dates in English with listening practice.",
"k390": "At the restaurant",
"k391": "Useful expressions and dialogues for ordering food and booking a table.",
"k392": "Coming soon",
"k393": "Intermediate and exam preparation",
"k394": "Higher-level files",
"k395": "40 useful words and expressions for travel and getting through the airport.",
"k396": "A practical summary of present, past, and future tenses with interactive practice.",
"k397": "IELTS vocabulary — part 1",
"k398": "High-frequency IELTS vocabulary with examples and correct pronunciation.",
"k399": "Part of the Vesta family?",
"k400": "Active learners get the full set of learning files and exclusive weekly exercises in their portal.",
"k401": "Sign in to the student portal"
};
  var KEY = 'vesta-lang';

  function readLang() {
    try {
      var q = new URLSearchParams(location.search).get('lang');
      if (q === 'en' || q === 'fa') return q;
    } catch (e) {}
    try { return localStorage.getItem(KEY) === 'en' ? 'en' : 'fa'; } catch (e) { return 'fa'; }
  }

  function apply(lang) {
    var root = document.documentElement;
    root.lang = lang;
    root.dir = lang === 'en' ? 'ltr' : 'rtl';

    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      if (el.getAttribute('data-fa') === null) el.setAttribute('data-fa', el.innerHTML);
      el.innerHTML = lang === 'en' ? EN[el.getAttribute('data-i18n')] : el.getAttribute('data-fa');
    });

    document.querySelectorAll('[data-i18n-attr]').forEach(function (el) {
      el.getAttribute('data-i18n-attr').split(';').forEach(function (pair) {
        var p = pair.split(':'), name = p[0], key = p[1], store = 'data-fa-' + name;
        if (el.getAttribute(store) === null) el.setAttribute(store, el.getAttribute(name) || '');
        el.setAttribute(name, lang === 'en' ? EN[key] : el.getAttribute(store));
      });
    });

    document.querySelectorAll('.lang-switch button').forEach(function (b) {
      b.setAttribute('aria-pressed', String(b.getAttribute('data-lang') === lang));
    });
  }

  /* helper for scripted messages: L('فارسی', 'English') */
  window.L = function (fa, en) { return document.documentElement.lang === 'en' ? en : fa; };

  document.querySelectorAll('.lang-switch button').forEach(function (b) {
    b.addEventListener('click', function () {
      var lang = b.getAttribute('data-lang');
      try { localStorage.setItem(KEY, lang); } catch (e) {}
      apply(lang);
    });
  });

  apply(readLang());
})();
